### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by peteranny** [peteranny/WindHorseNote#1]
# 首頁
- 中間
  - [x] 小風小馬
- 周圍
  - [x] 空格
  - [x] 墊子
  - [x] 墊子上有新的小風小馬
- 角落
  - [x] 圖鑑
  - [x] 背包
  - [x] 鈴鐺通知
  - [x] 目前鈴鐺

# Store
- Local Storage
  - [x] dehydrate on startup
  - [x] hydrate on save
- 架構
  - [ ] ~~上次更新時間戳~~
  - [x] 每個空格狀態(空格/墊子/墊子上的小風小馬ID/時間戳) `slots: { upperLeft: { itemIdentifier, creatureIdentifier, creatureArriveTime } }`
  - [x] 目前鈴鐺
  - [x] 背包每個墊子是否已購買
  - [x] 圖鑑每個小風小馬來訪次數
  - [x] 鈴鐺通知

# 小風小馬
- [x] 墊子上有小風小馬的時候，小風小馬會左右搖擺

# 分派小風小馬策略
- 每次刷新
  - [x] 時間戳會儲存至 store
  - [x] 若目前時間早於上次時間戳+1min，不更新
- 每次更新時間戳，會分派每個墊子的小風小馬
  - [x] 空的墊子：隨機/以墊子去選/以小風小馬去競爭墊子/... 有可能還是空的
  - [x] 若分派小風小馬到空墊子上，會記錄小風小馬ID和時間戳至 store
  - 有小風小馬的墊子
    - [x] 會比對該墊子時間戳的TTL，到期者會被移除
    - [x] 新增鈴鐺和鈴鐺通知
    - [x] 使墊子為空

# 背包
- 每個墊子
  - [x] ID
  - [x] desc
  - [x] 售價鈴鐺數
  - [x] 分派策略函數
  - [x] 是否已購買
  - [x] 是否已放入空格
- [x] 若尚未放入空格，則選擇放入哪個空格
- [x] 若已放入空格，則移出空格
- [x] 設計更多墊子

# 圖鑑
- 每個小風小馬
  - [x] ID
  - [x] desc
  - [x] 分派策略函數
  - [x] 來訪次數
  - [x] 設計更多小風小馬

# 鈴鐺通知
- 每個鈴鐺通知
  - [x] 小風小馬ID
  - [x] 鈴鐺數
  - [x] 已讀按鈕
